### ISSUE TITLE
app_name & app_path collisions

### ISSUE THREAD

**Issue by CrCs2O4** [Freika/rails_server#1]
First of all, thanks for great project, it really time-saver! Running ansible from scratch I run through couple issues & have some questions:
- app_name needs to be without domain, like WEBSITE ?
- app_path needs to be with domain, like /home/deploy/var/www/WEBSITE.COM/current/ ?

It's not straight from source, because somewhere it uses /home/deploy/var/www/nickshaker/current/public  and somewhere /home/deploy/var/www/middleman.dev/html

Also, ansible wanted file website.com (not website) at /roles/nginx/templates/

And I need to run couple commands manually to get things work (maybe I get smth wrong or if not, it can be automated too):

```
# strange problem with access writes - why directory was created under root user?
sudo chown -R deploy:deploy /home/deploy/var
# make upload_db/tasks/main.yml working
mkdir /home/deploy/var/www/website.com/shared/config
# install gems
cd /home/deploy/var/www/website.com/current
bundle install --without development test
```

Thanks for Telegram chatting! 😄

**Comment by CrCs2O4** [comment]
After couple server OS reinstalling I understand, that all manual commands above is deployer tool business, not ansible 😄  also switched from capistrano to [mina](http://nadarei.co/mina/)

By the way, I deleted default nginx config, case it messing things up and don't used at all (roles/nginx/tasks/configure.yml)

Also I had bug with task "restore db" - when it use directive 'command' I finished up with no tables in db, switched to 'shell'.

```
# roles/upload_db/tasks/main.yml

- name: Restore db form dump
  shell: "psql {{ app_name }}_production < /home/deploy/var/www/{{ app_name }}/shared/{{ app_name }}.sql -U {{ app_name }}"
```

Now everything goes smooth 👍

**Comment by CrCs2O4** [comment]
Created [PR: RestoreDB command fix](https://github.com/Freika/rails_server/pull/3).

You can close this issue. Thanks!

**Comment by Freika** [comment]
#3 solved
